import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { merriweather, poppins } from "@/styles/fonts";
import theme from '@/app/components/theme/theme';
import { ThemeProvider } from "@mui/material/styles";
import "@/styles/globals.css";
import DashboardLayout from '@/app/components/dahboard/layout';

/**
 * 2 types of metadata.
 * static: metadata: Metadata
 * dynamic: (generateMetadata) it is based on different routes, params etc.
 */
export const metadata: Metadata = {
  title: "GOGO Form Management App",
  description: "We can control the all forms here. For example, inspection form request etc.",
  icons: {
    icon: `${process.env.NEXT_PUBLIC_CDN_URL}/b2cpages/favicon.ico`,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${poppins.className} ${merriweather.className}`}>
      {/* The AppRouterCacheProvider component is responsible for collecting the
       CSS generated by MUI System on the server, as Next.js is streaming chunks
      of the .html page to the client. */}
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <DashboardLayout>{children}</DashboardLayout>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
